### ISSUE TITLE
Elasticsearch: max virtual memory areas vm.max_map_count [xxxx] is too low, increase to at least [xxxx]

### ISSUE THREAD

**Issue by FFrozTT** [creekorful/trandoshan#10]
I'm seeing a lot more results than before but also API errors on URL's I know to be working:

time="2020-08-10T20:40:42Z" level=error msg="Error getting response from ES: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host"

**Comment by creekorful** [comment]
I've run the crawler for 2hours today and didn't notice anything. This error is due to a resolution error. It may happen if the elasticsearch instance isn't started yet or if it's down (maybe memory overhead?) Can you check the elasticsearch process status?

You can do it by running:

```
docker-compose -f deployment/docker-compose.yml ps
```

**Comment by FFrozTT** [comment]
Looks like it may have exited ...?

           Name                          Command                  State                  Ports
----------------------------------------------------------------------------------------------------------
deployments_api_1             ./api --log-level debug -- ...   Up             0.0.0.0:15005->8080/tcp
deployments_crawler_1         ./crawler --log-level debu ...   Up
deployments_elasticsearch_1   /usr/local/bin/docker-entr ...   Exit 137
deployments_kibana_1          /usr/local/bin/dumb-init - ...   Up             0.0.0.0:15004->5601/tcp
deployments_nats_1            nats-server                      Up             4222/tcp, 6222/tcp, 8222/tcp
deployments_persister_1       ./persister --log-level de ...   Up
deployments_scheduler_1       ./scheduler --log-level de ...   Up
deployments_torproxy_1        /sbin/tini -- /usr/bin/tor ...   Up (healthy)   8118/tcp, 9050/tcp, 9051/tcp

**Comment by creekorful** [comment]
Unfortunately looks like it's the problem. Elasticsearch is very demanding in memory.

I'll take a look at official documentation and how much memory other people give

**Comment by FFrozTT** [comment]
Yes I went up to 4GB and it seems to be running without exiting now.  The reason I've been so frugal with memory is because i'm using a DO Droplet and going from 1GB to 4GB quadruples the price.  However that's my problem not yours.  You can close this issue.
