### ISSUE TITLE
Add switches to docker-compose allowing detaching

### ISSUE THREAD

**Issue by FFrozTT** [creekorful/trandoshan#11]
Add -t -i switches to docker command allowing detaching.  Right now I have to restart the whole project if I want to attach/detach.

Alternatively, you could assign unique detach keys:

--detach-keys "ctrl-a,a"

Sorry, I was trying to add an "Enhancement label" but I don't think I can

**Comment by creekorful** [comment]
> Sorry, I was trying to add an "Enhancement label" but I don't think I can

Yes you cannot, this option is only allowed for repository member.

> Add -t -i switches to docker command allowing detaching. Right now I have to restart the whole project if I want to attach/detach.

I don't really understand your problem. Are you talking about the docker-compose being attached to his parent process ? (i.e when running start.sh you cannot close the window) or are you talking about something else?

**Comment by FFrozTT** [comment]
When I attach one of the containers (say the API for example) to view it's stdout, there is no graceful way to detach leaving me with no choice but to ctrl-c which kills the container.  If you supply the -t -i switches when creating the container, I would be able to use ctrl-q+ctrl-a to detach without killing the container.

**Comment by creekorful** [comment]
> When I attach one of the containers (say the API for example) to view it's stdout, there is no graceful way to detach leaving me with no choice but to ctrl-c which kills the container. If you supply the -t -i switches when creating the container, I would be able to use ctrl-q+ctrl-a to detach without killing the container.

When running ``./scripts/start.sh`` you should be able to view the STDOUT of all running processes.
If you want to view one particular in details you can run ``./scripts/log.sh api`` for example.

Is that what you want?

**Comment by FFrozTT** [comment]
I may launch start.sh from one ssh session, then come back later in a completely different session, so the original tty is long lost.

I see you added a log.sh script. That essentially mirrors what I was looking for.  Thanks.

**Comment by creekorful** [comment]
@FFrozTT otherwise you can use something like [tmux](https://github.com/tmux/tmux/wiki) for this purpose. 
This is what I use to always have a running irc client and not lose all the logs.
