### ISSUE TITLE
Problems crawling torch results pages

### ISSUE THREAD

**Issue by FFrozTT** [creekorful/trandoshan#15]
For some reason the crawler is not parsing Torch results pages correctly because none of the links end up being scheduled or crawled.

e.g.

http://xmh57jrzrnw6insl.onion/4a1f6b371c/search.cgi?s=DRP&q=irc&cmd=Search%21

Should return plenty of results.

I have no idea why, the only thing remotely interesting is that there is an iframe at the start of the page. I think I've seen this with some other pages too but I can't remember what they were.

**Comment by creekorful** [comment]
Hello there! That's a error from me.
The scheduler is removing fragments and query parameters from the URL. For the query parameters that's an error to remove them since they may affect page content. This cleanup should definitely be removed.

**Comment by creekorful** [comment]
I was wrong, this cleanup has been removed months ago.
Do you mind sharing the logs so that we can investigate?

**Comment by FFrozTT** [comment]
Is there some other logs? All I have are these ones:

```
api_1            | time="2020-09-03T05:18:51Z" level=debug msg="Successfully published URL: http://xmh57jrzrnw6insl.onion/4a1f6b371c/search.cgi?s=DRP&q=irc&cmd=Search%21"
scheduler_1      | time="2020-09-03T05:18:51Z" level=debug msg="Processing URL: http://xmh57jrzrnw6insl.onion/4a1f6b371c/search.cgi?s=DRP&q=irc&cmd=Search%21"
```

Nothing ever hits the crawler

**Comment by creekorful** [comment]
This looks strange, have you tried running `./scripts/log.sh scheduler` ?

**Comment by FFrozTT** [comment]
ya, that's where this one comes from:
`scheduler_1      | time="2020-09-03T05:18:51Z" level=debug msg="Processing URL: http://xmh57jrzrnw6insl.onion/4a1f6b371c/search.cgi?s=DRP&q=irc&cmd=Search%21"`

**Comment by creekorful** [comment]
I need to check the DOM of the page, maybe there's something in there that's causing trouble to the crawler.

**Comment by creekorful** [comment]
```
 $ curl --socks5-hostname localhost:9050 'http://xmh57jrzrnw6insl.onion/4a1f6b371c/search.cgi?s=DRP&q=irc&cmd=Search%21'
[...]
<h2>This domain has been migrated to Onion version 3.</h2>
[...]
From now on, to access <b>Torch: Tor Search Engine</b> service you must use this Onion domain name:<br><br>
     <a href="http://xmh57jrknzkhv6y3ls3ubitzfqnkrwxhopf5aygthi7d6rplyvk3noyd.onion"><h3>xmh57jrknzkhv6y3ls3ubitzfqnkrwxhopf5aygthi7d6rplyvk3noyd.onion</h3></a><br><br>
[...]
```
Looks like these links are not valid anymore. The server is returning a HTTP 404 (no redirection) so there's no way for the crawler to find the page. Maybe try to crawl again with the updated torch URL?

**Comment by FFrozTT** [comment]
Oh strange, it didn't look like that when I was testing this a few days ago, at the time that page was loading normally in a browser.

In any case, it does appear to be working with that new link as I'm seeing a lot of results pour in now. Sorry for the false alarm.

**Comment by creekorful** [comment]
No problem at all!

BTW I'm a bit curious, why do you exactly give Trandoshan a try? Personal project? Company? Student? Just for fun?
I'm happy to know that people are still interested in it :)

If you are up to, let's talk about this by whatever communication support you want to use.
Full list of my communication support is available here: https://creekorful.dev
