### ISSUE TITLE
Elasticsearch Crashing with Code 127

### ISSUE THREAD

**Issue by GaganBhat** [creekorful/trandoshan#17]
I'm running this on a Google Cloud Platform compute instance with 8GB RAM and 2 cores. 

When I open the Kibana dashboard and create a canvas with a data table of the crawled content from resources *, it appears to lag for a brief moment and later give me 401 unauth errors. 

In the console, I see that `docker_elasticsearch_1 exited with code 127` 

Memory usage at the time of crash doesn't seem to be high either, with around 2/8GB RAM being used. 

```
scheduler_1      | time="2020-09-07T03:53:12Z" level=info msg="Successfully initialized tdsh-scheduler. Waiting for URLs"
torproxy_1       | WARNING: no logs are available with the 'none' log driver
// After opening kibana dashboard and waiting about 20 seconds
docker_elasticsearch_1 exited with code 127
```

**Comment by creekorful** [comment]
Hello there,

Some questions to help us figure this out:
- Are you using the default config file?
- Are you using the latest version?
- Do you mind sharing the whole logs ? `docker-compose logs --no-color > logs.txt`
- How much data have you already crawled?

**Comment by GaganBhat** [comment]
Thanks for responding, 

1. Are you using the default config file?
Yes, I am. Did not make any changes after cloning the repo.
2. Are you using the latest version?
Yes, I pulled yesterday. 
3. Do you mind sharing the whole logs ? docker-compose logs --no-color > logs.txt
Yep, although this seems to just be a bunch of processing logs. https://0x0.st/i6Or.txt
4. How much data have you already crawled?
Unsure how I can check this information. I just ran a test command for the facebook onion mirror.

**Comment by creekorful** [comment]
> Thanks for responding, appreciate all the work you do on this project.

Thank you!

> Yep, although this seems to just be a bunch of processing logs. https://0x0.st/i6Or.txt

You're right, despite it looks like NATS server is down too:

```
$ grep 'level=error' i6Or.txt
[...]
scheduler_1      | time="2020-09-07T04:44:46Z" level=error msg="Error while connecting to NATS server nats: nats: no servers available for connection"
scheduler_1      | time="2020-09-07T04:45:47Z" level=error msg="Error while connecting to NATS server nats: nats: no servers available for connection"
scheduler_1      | time="2020-09-07T04:46:47Z" level=error msg="Error while connecting to NATS server nats: nats: no servers available for connection"
```
this may be an indicator of memory pressure, but not sure at this time.

Let's try something simple first,
Can you enable logging for the ES container? This will greatly help us.

You just need to remove the logging configuration section: https://github.com/creekorful/trandoshan/blob/42ee9301606efebd7ed537a63270f20bbe684137/deployments/docker/docker-compose.yml#L14

**Comment by GaganBhat** [comment]
It appears to be an OutOfMemoryError (even though it isn't using all my system RAM available. Limited by args maybe?) 
Here's the log with elasticsearch -- https://0x0.st/i64w.txt

**Comment by creekorful** [comment]
Looks like the docker-compose.yml config file is wrong.

> warning: ignoring JAVA_OPTS=-Xms2g -Xmx2g; pass JVM parameters via ES_JAVA_OPTS

Can you try renaming the parameters in the file and see if that's work?

**Comment by GaganBhat** [comment]
Thanks, that seems to have fixed it for now (Kibana did crash on me one time with code 134 but just restarted it and it seems to run fine now.)

Also, I just want to ask, how can I delete all the data of the URLs I have scrubbed already so that I can reset my environment start crawling new ones?

**Comment by creekorful** [comment]
> Also, I just want to ask, how can I delete all the data of the URLs I have scrubbed already so that I can reset my environment start crawling new ones?

You can simply delete the whole compose instance by running `./scripts/delete.sh` on unix.
The next time you start the crawler it will recreate everything.

**Comment by creekorful** [comment]
I'm closing the issue as it's fixed, feel free to re-open it / open a new one if needed,
Cheers!

**Comment by GaganBhat** [comment]
Thanks. 
> The next time you start the crawler it will recreate everything.

Last question, what if I don't want it to recreate everything? Just remove the data and go back to the blank initial state where it waits for a new URL to be scheduled.

**Comment by creekorful** [comment]
That's exactly what delete.sh will do. It will clear the elasticsearch instance completely. You'll just need to re-configure it. 
If you want to keep the configuration maybe you'll need to delete the elasticsearch index trough Kibana.
