### ISSUE TITLE
Duplicate URLs in ElasticSearch DB

### ISSUE THREAD

**Issue by woonhulktin** [creekorful/trandoshan#21]
Hi there,

I've been playing with this Tor crawler for some time and generally it works pretty well. However, I've got a problem of duplicate urls. It has been running for 4 days and has achieved over 4000 hits, but the count of unique urls is just around 1000.

I noticed that there is a query method in the scheduler that asks the ElasticSearch DB whether the found url already exists. 
```python
b64URI := base64.URLEncoding.EncodeToString([]byte(normalizedURL.String()))
apiURL := fmt.Sprintf("%s/v1/resources?url=%s", apiURI, b64URI)

var urls []proto.ResourceDto
r, err := httpClient.JSONGet(apiURL, &urls)
...
if len(urls) == 0 {
...
```
I've copied this method to the crawler and persister as well to check todo urls and resource urls. However, it still only gets around 1000 unique urls out of over 4000 hits. 

Does anyone have any idea of how to fix this problem? Any hint would be greatly appreciated.

**Comment by creekorful** [comment]
Hello there!

> I've copied this method to the crawler and persister as well to check todo urls and resource urls. However, it still only gets around 1000 unique urls out of over 4000 hits.

It is not the crawler job to knows if something should be crawled, that's what the scheduler is designed for.

Basically each urls found by crawlers are push into a queue named `url.found` and the scheduler read from it determinate if the url should be crawled, and if so push it into the `url.todo` queue.

I'm not sure where is the error exactly, I will investigate this, thanks for your report!

**Comment by woonhulktin** [comment]
Hi Aloïs,

Thank you for your quick reply! I just realised that querying the ElasticSearch DB in the crawler and persister is redundant and not useful. But I also got one idea. The reason could be that the scheduler only queries the ElasticSearch DB but does not check duplicate in `url.todo`. If an url in the `url.found` queue is not in the ElasticSearch DB but is already in the `url.todo` queue, then eventually it will lead to a duplicate in the DB. So I think adding a function that checks duplicates in the `url.todo` queue may solve this issue. 

Haotian

**Comment by creekorful** [comment]
Indeed this may be the issue! Nice catch.
I remember having this exact issue (https://github.com/trandoshan-io/scheduler/issues/7) on the first Trandoshan build.

Your idea will certainly work in simple setup (one scheduler) but in distributed environment this will be the hell to deal with.
I'm pretty sure these issues exist because of the bad architecture I have designed, I'm trying to improve it a scaleable way (see #16).

I'm looking for help so if you wanna contribute it will be greatly appreciated :)

**Comment by woonhulktin** [comment]
I have one idea that the `url.todo` is also written into a DB so that every crawler can subscribe to it and checking duplicate would also be easier. I'm happy to contribute and I'll also look into other possible ways to fix the bug.

**Comment by creekorful** [comment]
Hello @woonhulktin the latest release of Trandoshan should mitigate this issue.

**Comment by woonhulktin** [comment]
Hi @creekorful  Thank you for your great job! I'm running it and I'll check the new results later.
