### ISSUE TITLE
Create dashboard application

### ISSUE THREAD

**Issue by creekorful** [creekorful/trandoshan#25]
The idea is to have a simple JS (angular? react? vue?) application that will dial with the API to get insight from the crawler.

- Resource page to view / search resources using input
- Page to submit URL to crawl
- ?

If anyone has suggestion, feel free to comment on this PR!

**Comment by smit1759** [comment]
You could always create some dashboards in Kibana?

**Comment by creekorful** [comment]
> You could always create some dashboards in Kibana?

It is actually what we are doing! 
I wanted to make something different & easier to use than Kibana.
