### ISSUE TITLE
Build Error invalid argument "creekorful/"

### ISSUE THREAD

**Issue by blueteamzone** [creekorful/trandoshan#39]
Hi, docker version is `19.03.12`, we tried to build trandoshan using the scripts `build.sh`. However it gives the following errors:

`invalid argument "creekorful/" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.`

Where can we find the documentation on this project? Thanks

**Comment by blueteamzone** [comment]
Managed to get it working! Thanks

**Comment by creekorful** [comment]
Glad to know you manage to get this working! Was it an error on your side or have you found a bug?

**Comment by blueteamzone** [comment]
It was an error on our side. We ran 'build.sh' before running 'start.sh'.
