### ISSUE TITLE
Feeder to API unmarshaling error

### ISSUE THREAD

**Issue by FFrozTT** [creekorful/trandoshan#7]
I can't get that new feeder to work, am I doing it wrong?

```
./cmd/feeder/feeder --api-uri http://localhost:15005 --url https://www.facebookcorewwwi.onion
INFO[0000] Starting trandoshan-feeder v0.0.1
INFO[0000] URL https://www.facebookcorewwwi.onion successfully sent to the crawler
```

```
api_1            | time="2020-08-08T03:15:21Z" level=error msg="Error while un-marshaling url: invalid character 'h' looking for beginning of value"
```

Maybe missing some json encoding?  I'm not sure, I tried passing json encoded values too but it didn't like them any better than a raw url.

**Comment by creekorful** [comment]
Hello @FFrozTT, this was indeed an error, I was using curl to publish URL locally and forgot to test the feeder.

Thank you!
