### ISSUE TITLE
%!s(<nil>) response

### ISSUE THREAD

**Issue by FFrozTT** [creekorful/trandoshan#8]
I'm having that [previous issue ](https://github.com/creekorful/trandoshan/issues/6)again with the new build:

scheduler_1      | time="2020-08-08T17:17:49Z" level=debug msg="Processing URL: https://www.facebookcorewwwi.onion"
api_1            | time="2020-08-08T17:17:49Z" level=debug msg="Successfully published URL: https://www.facebookcorewwwi.onion"
api_1            | time="2020-08-08T17:17:49Z" level=error msg="Error getting response: %!s(<nil>)"
scheduler_1      | time="2020-08-08T17:17:49Z" level=error msg="Error while searching URL: %!s(<nil>)"
scheduler_1      | time="2020-08-08T17:17:49Z" level=error msg="Received status code: 500"

**Comment by creekorful** [comment]
I'll confirm the bug once I get home. Thank you!

**Comment by creekorful** [comment]
Bug confirmed.

**Comment by creekorful** [comment]
Done. Thank you again!
